name: Test Suite

# Run against all commits and pull requests.
on: [ push, pull_request ]

jobs:
  test_matrix:

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ruby:
          - 2.1
          - 2.2
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - 3.0
          - head
          - jruby
          - jruby-head
          - truffleruby
          - truffleruby-head

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.68.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake

  finish:
    runs-on: ubuntu-latest
    needs: [ test_matrix ]
    steps:
      - name: Wait for status checks
        run: echo "All Green!"
